/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(b){if(b.__qc)return b.__qc;var s=b.document,x=b.navigator,N="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),O=!1,g=0,f=[],z=[],D=[],G={tcYgbCswcTSeq:1,"01-0VIaSjnOLg":1,aD1qr93XuF6aC:1,"56WJ0KtIxWJ_2":1,T1nhLcmCjVzQS:1,zddNYNtUkUhdQ:1,"59TntzuqummDw":1,P7x87XHnVfbWr:1,HGAVM7nQJ_sep:1,"w9vzus-GKCA0U":1,"00TsOkvHvnsZU":1,effSsmMYCbAck:1,PFW5FesqXn206:1,
"0dYLvhSGGqUWo":1,c1rF4kxgLUzNc:1,"5brKQLtleyIQU":1,"mEzuYq24VEJ-3":1,"57OGVHgSOoedo":1,"e7wR0qsM6-pDa":1,"8tgFhCTDYhV2V":1,"82MbSinIaQJw2":1,buQ2dAnrdTGCS:1,"49SVsgIZlUqPk":1,eeFYJkotb1rUU:1,EzVU5HfAMVqEV:1,"45nh8QKbsf2Xk":1,sLJ2v5QaN4z2Y:1,"5cvC4NOeGmtNA":1,"573scDfDoUH6o":1,"915Y6SMHQQJHI":1,z0zMG4nCgXzzj:1,"124BfeS-bwiSE":1,"ZzStSGgW6hG-4":1,KUMT4fYgcdEeg:1,d9vfr8QTWnv1E:1,fug7wP0GuN1h6:1,cd12aNCzw_ZaB:1,"51zXP5Cc9sxvQ":1,"4dIM5nVs2rFio":1,"8fZNjMQsH1Ews":1,C6W3aFrWFMS7m:1,N7ekbgK3G3jrt:1,dfQGRefil9mes:1,
"9axVJDmh4EHIM":1,NPcfSf1E0V1T1:1,"72V4-XKpaKDrE":1,"8cV3w6ZJH0sXI":1,sHwqAaPHqVjee:1,b15U9CAASyBMc:1},p=[],w={},H=0,I=[],E=null,Y={},y={},ja=null,t,Z=[].slice,ka,$,P,q,A,aa,Q,la,ma,na,J,ba,R,S,oa,K,pa,qa,ra,sa,v,ta,B,T,ua,ca,va,wa,da,r,xa,ea,U,V,ya,za,W,Aa,fa,ga,Ba,ha,F,L,M,X,ia,u=function(a){try{return{init:S,hash:R,rules:ya,hasRules:W,defaults:Ba,__qc:function(){return!0}}[a].apply(null,Z.call(arguments,1))}catch(c){return!1}};u.evts=0;u.v=2;u.SD=N;u.qpixelsent=[];V=function(a){var c=a?a.length||
0:0,d;for(d=0;d<c;d++)if(!a[d])return!1;return!0};ga=function(a){(a=a||b._qacct)&&(da(p,a)||p.push(a))};da=function(a,c){var d=a.length,b;for(b=0;b<d;b++)if(a[b]===c)return!0;return!1};ea=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};U=function(a){var c,d;c=ea(a);if("array"===c)return a.slice(0);if("object"===c){c={};for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c}return"string"===c?""+a:a};W=function(a){return da(D,a)};Ba=function(a,c){var d;a&&((d=Y[a])&&(c=
X(c,d)),c.qacct&&delete c.qacct,Y[a]=c)};ha=function(a){var c,d;if(q(a))for(c in a)if("string"==typeof a[c]){c=a.event||"load";d=a.media||"webpage";"rule"!==c&&"load"!==c||"webpage"!==d&&"ad"!==d?v(a):(d=a.qacct||b._qacct,a.qacct=d,c=(c=y[d])?X(c,a):a,y[d]=c);ga(a.qacct);break}else"object"==typeof a[c]&&null!=a[c]&&ha(a[c])};X=function(a,c){var d={};d.qacct=a.qacct||c.qacct;d.event="load"===a.event||"load"===c.event?"load":a.event&&c.event?a.event||c.event:null;d.media=null;d.media="webpage"===a.media||
"webpage"===c.media?"webpage":"ad"===a.media||"ad"===c.media?"ad":a.media||c.media;ca(d,a,c);ca(d,c,a);d.event||delete d.event;d.media||delete d.media;return d};ca=function(a,c,d){var b,h,l,C,g,m;for(b in c)c.hasOwnProperty(b)&&!a.hasOwnProperty(b)&&(h=c[b],l=d[b],C="",g=!!h&&"string"==typeof h,m=!!l&&"string"==typeof l,g&&(C=h),g&&m&&(C+=","),m&&(C+=l),a[b]=C)};F=function(){var a=[],c,d;if(!(0<H)){xa();for(c in y)y.hasOwnProperty(c)&&y[c]&&(d=y[c],a.push(d),delete y[c]);1==a.length&&v(a[0]);1<a.length&&
v(a)}};L=function(a){var c=[],d,b;for(d=0;d<a.length;d++)b=a[d],G.hasOwnProperty(b.substring(2))?w[b]=5:W(b)||c.push(b);if(0===c.length)F();else for(d=0;d<c.length;d++)b=c[d],D.push(b),va(b)};wa=function(){for(var a;I[0]&&("loaded"==I[0].readyState||"complete"==I[0].readyState);)a=I.shift(),a.onreadystatechange=null,E.parentNode.insertBefore(a,E),M()};va=function(a){var c,d;c=("https:"===s.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+a+".js";E=E||s.scripts[0];H++;d=s.createElement("script");
"async"in d?(d.src=c,d.async=!1,d.onload=function(){w[a]=0;M()},d.onerror=function(){w[a]=1;M()},E.parentNode.insertBefore(d,E)):d.readyState?(w[a]=2,I.push(d),d.onreadystatechange=wa,d.src=c):(w[a]=4,M())};M=function(){H-=0<H?1:0;F()};ya=function(){var a=!0,c,d,b;if(arguments.length){b=function(c){a?ha(c):v(c,!0)};for(c=0;c<arguments.length;c++)d=Z.call(arguments[c],0),d.splice(1,0,b),za.apply(null,d);a=!1;O&&F()}};za=function(a,c){var b=[],e=[],h=c||v,l,g,f,m,n;if((l=Z.call(arguments,2))&&l.length){g=
l[0]||V;f=l[1];m=l[2];l=m.length;for(n=0;n<l;n++)b.push(!1),e.push(null);b={p:a,f:b,r:g,c:m,a:f,v:e};W(a)||D.push(a);z.push(b);Aa(b,h)}};Aa=function(a,c){var b=a?a.c?a.c.length:0:0,e;for(e=0;e<b;e++)(function(b){var d,e;try{d=a.c[b][0],e=a.c[b].slice(1),e.splice(0,0,function(d){a.f[b]=!0;a.v[b]=d;fa(a,c)}),d.apply(null,e)}catch(g){a.f[b]=!0,a.v[b]=!1,fa(a,c)}})(e)};fa=function(a,c){var b=a.a,e=a.v,h=a.r||V,l,g,f,m,n,k;(l=V(a.f))&&(l=l&&h(e));if(l)for(e=0;e<b.length;e++)try{g=b[e][0];f=1<b[e].length?
b[e].slice(1):[];f=f.concat(a.v);m=g.apply(null,f);n={qacct:a.p,event:"rule"};for(k in m)m.hasOwnProperty(k)&&"qacct"!==k&&(n[k]=m[k]);c(n)}catch(q){}};ka=function(){return $(0)!==$(6)?1:0};$=function(a){a=new Date(2E3,a,1,0,0,0,0);var c=a.toGMTString(),c=new Date(c.substring(0,c.lastIndexOf(" ")-1));return a-c};P=function(a){return a.replace(/\./g,"%2E").replace(/,/g,"%2C")};A="function"===typeof encodeURIComponent?encodeURIComponent:P;q=function(a){return"undefined"!=typeof a&&null!=a};aa=function(){return Math.round(2147483647*
Math.random())};Q=function(a){var c="",b=s.cookie,e;if(!b)return c;e=b.indexOf(a+"\x3d");a=e+a.length+1;-1<e&&(c=b.indexOf(";",a),0>c&&(c=b.length),c=b.substring(a,c));return c};la=function(){var a="",c=J(),b,e,h;if(1===g)return";fpan\x3du;fpa\x3d";b=R(c);for(e=0;e<N.length;e++)if(N[e]===b)return";fpan\x3du;fpa\x3d";b=new Date;e=Q("__qca");if(0<e.length){try{h=+e.split("-")[2],338688E5<b-h&&(s.cookie=["__qca\x3d",e,"; expires\x3d",(new Date(h+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""))}catch(l){}a+=
";fpan\x3d0;fpa\x3d"+e}0===Q("__qca").length&&(e="P0-"+aa()+"-"+b.getTime(),s.cookie=["__qca\x3d",e,"; expires\x3d",(new Date(b.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""),e=Q("__qca"),a=0<e.length?a+(";fpan\x3d1;fpa\x3d"+e):a+";fpan\x3du;fpa\x3d");return a};ma=function(a){s.cookie=a+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+J()};J=function(){var a,c,b,e;a=s.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));c=a.split(".");e=c.length;
if(3>e)return a;b=c[e-1];return 3>b.length?a:a=c[e-2]+"."+b};ba=function(a,c){var b;for(b=0;b<c.length;b++)a^=c.charCodeAt(b),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};R=function(a){var c;c=ba(2166136261,a);a=ba(3386659096,a);return Math.round(Math.abs(c*a)/65536).toString(16)};T=function(a,c,d){var e="",h=b._qacct,l=null,f="webpage",z="load",m={},n,k,h=c?c.qacct||b._qacct:b._qacct;n=y[h];c?n&&(c=X(c,n)):c=n;h&&delete y[h];if(null!=c)for(k in c)m[k]=!0,c.hasOwnProperty(k)&&"string"===typeof k&&
"string"===typeof c[k]&&("uid"===k||"uh"===k?(oa()||(l=R(c[k])),delete c[k]):"qacct"!==k&&(0<c[k].length?e+=";"+k+a+"\x3d"+A(c[k]):m[k]=!1,"media"===k&&(f=c[k]),"event"===k&&(z=c[k])));if("string"!==typeof h){if(!q(b._qacct)||0===b._qacct.length)return"";h=b._qacct}if(h&&(n=Y[h]))for(k in n)"string"===typeof k&&n.hasOwnProperty(k)&&!m[k]&&(e+=";"+k+a+"\x3d"+A(n[k]),"media"===k&&(f=n[k]),"event"===k&&(z=n[k]));m=w[h];q(m)||(m=3);e+=";rf"+a+"\x3d"+m;"string"===typeof l&&(c.uh=l,e+=";uh"+a+"\x3d"+A(l));
if("webpage"===f&&"load"===z){for(c=0;c<u.qpixelsent.length;c++)if(u.qpixelsent[c]===h&&!d)return"";u.qpixelsent.push(h)}"ad"===f&&(g=1);return";a"+a+"\x3d"+h+e};ua=function(){var a=s.getElementsByTagName("meta"),c="",b,e,h,f;for(b=0;b<a.length;b++){h=a[b];if(1E3<=c.length)return c;q(h)&&q(h.attributes)&&q(h.attributes.property)&&q(h.attributes.property.value)&&q(h.content)&&(e=h.attributes.property.value,h=h.content,3<e.length&&"og:"===e.substring(0,3)&&(0<c.length&&(c+=","),f=80<h.length?80:h.length,
c+=P(e.substring(3,e.length))+"."+P(h.substring(0,f))))}return A(c)};na=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};oa=function(){var a=!1;q(b.external)&&(a=b.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());return a||"1"==x.doNotTrack||"yes"===x.doNotTrack||"1"==x.msDoNotTrack};v=function(a,c){var d="function"===typeof encodeURIComponent?"n":"s",e=aa(),h="",l="",z="",D="",m="",
n="u",k="1",p=0,G=[],r,t,v,w;g=0;q(u.qpixelsent)||(u.qpixelsent=[]);if(q(a))for(r in a)if("string"==typeof a[r]){l=T("",a,c);break}else"object"==typeof a[r]&&null!=a[r]&&(++p,l+=T("."+p,a[r],c));else"string"===typeof _qacct&&(l=T("",null,c));0!==l.length&&(p=x.cookieEnabled?"1":"0","undefined"!=typeof x.javaEnabled&&(n=x.javaEnabled()?"1":"0"),q(b._qmeta)&&(z=";m\x3d"+A(b._qmeta),b._qmeta=null),self.screen&&(h=screen.width+"x"+screen.height+"x"+screen.colorDepth),t=new Date,v=ka(),w=la(),b.location&&
b.location.href&&(D=A(b.location.href)),s&&s.referrer&&(m=A(s.referrer)),b.self===b.top&&(k="0"),r=ua(),G.push("/pixel;r\x3d"+e+l+w+";ns\x3d"+k+";ce\x3d"+p),G.push(";je\x3d"+n+";sr\x3d"+h+";enc\x3d"+d+";dst\x3d"+v+";et\x3d"+t.getTime()+";tzo\x3d"+t.getTimezoneOffset()+z+";ref\x3d"+m+";url\x3d"+D+";ogl\x3d"+r),f.push(G),B())};ta=function(a){var c=new Image;a=[b.location.protocol,"//pixel.",pa(t)?"quantserve.com":"quantcount.com",a[0],";cm\x3d",na(t),a[1]].join("");c.alt="";c.src=a;c.onload=function(){c&&
"number"==typeof c.width&&3===c.width&&ma("__qca")}};B=function(){if(t)for(;f.length;)ta(f.shift());else sa()};pa=function(a){return!0===a||1===a||1===a||q(a)&&"approved"===a.consent?!0:!1};sa=function(){if(!q(t)){if(b.top===b.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){qa("getConsent","advertising");return}}else if(b.postMessage&&"object"===typeof JSON){ra("getConsent","advertising");return}t=1}B()};qa=function(a,b){t=PrivacyManagerAPI.callApi(a,"quantserve.com",
J(),"truste.com",b);B()};ra=function(a,c){var d={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:a,self:"quantserve.com",domain:J(),authority:"truste.com",type:c}};if(b.addEventListener)b.addEventListener("message",K,!1);else if(b.attachEvent)b.attachEvent("onmessage",K);else{t=!0;B();return}try{b.top.postMessage(JSON.stringify(d),"*")}catch(e){}ja=setTimeout(function(){q(t)||(t=!0,B())},25)};K=function(a){var c=null;if(a.source===window.top){try{c="object"===typeof JSON&&JSON.parse(a.data)}catch(d){}c&&
"object"===typeof c.PrivacyManagerAPI&&(clearTimeout(ja),b.removeEventListener?window.removeEventListener("message",K,!1):b.detachEvent&&window.detachEvent("onmessage",K),t=c.PrivacyManagerAPI,B())}};ia=function(){var a=arguments,b,d;r([].slice.call(a));for(d=0;d<a.length;d++)b=a[d],v(b);p.length?L(p.slice(0)):F()};r=function(a){var c=ea(a);if("array"===c)for(c=0;c<a.length;c++)r(a[c]);else"object"===c&&ga(a.qacct||b._qacct)};xa=function(){var a;b._qevents.length||b.ezt.length||"undefined"===typeof _qacct||
v({qacct:b._qacct});if(!u.evts){for(a in b._qevents)b._qevents.hasOwnProperty(a)&&v(b._qevents[a]);for(a in b.ezt)b.ezt.hasOwnProperty(a)&&v(b.ezt[a]);b._qevents={push:ia};b.ezt.push=function(){var a=arguments,d;if(q(b.queueManager))for(d=0;d<a.length;d++)b.queueManager.push(a[d]);else ia.apply(this,arguments)};u.evts=1}};S=function(){var a;q(b._qevents)||(b._qevents=[]);q(b.ezt)||(b.ezt=[]);b._qoptions&&(a=U(b._qoptions),r(b._qoptions),b._qevents.push(a),b._qoptions=null);b.qcdata&&(a=U(b.qcdata),
r(b.qcdata),b._qevents.push(a),b.qcdata=null);b.smarttagdata&&(a=U(b.smarttagdata),r(b.smarttagdata),b._qevents.push(a),b.smarttagdata=null);u.evts||(b._qevents.push=function(){r([].slice.call(arguments));L(p.slice(0));return[].push.apply(b._qevents,arguments)},b.ezt.push=function(){r([].slice.call(arguments));L(p.slice(0));return[].push.apply(b.ezt,arguments)});r(b.ezt);r(b._qevents);r({qacct:b._qacct});b._qoptions=null;p.length?L(p.slice(0)):F();O=!0};b.quantserve=b.quantserve||S;u.quantserve=S;
return u}(window);
try{__qc("hasRules","p-2-QREZmSntvyD")||function(b,s,x){try{__qc("defaults",b,{labels:"_fp.event.Default"})}catch(N){}var O=function(b,f,g){return b?"nc"===b?!f||!g||0>f.indexOf(g):"eq"===b?f===g:"sw"===b?0===f.indexOf(g):"ew"===b?(b=f.length-g.length,f=f.lastIndexOf(g,b),-1!==f&&f===b):"c"===b?0<=f.indexOf(g):!1:!1},g=function(b,f,g){var p;if(s.top===s.self)p=x.location.href;else{p=x.referrer;var w=x.createElement("a");w.href=p;p=w.href}O(f,p,g)?b(p):b(!1)},f=function(b){return"array"==={}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()?
{labels:b.join(",")}:{labels:""+b}};__qc("rules",[b,null,[[f,"_fp.event.World Campus Homepage"]],[[g,"eq","http://www.worldcampus.psu.edu/"]]],[b,null,[[f,"http://www.worldcampus.psu.edu/about-us"]],[[g,"eq","_fp.event.About Us"]]],[b,null,[[f,"_fp.event.Request Information"]],[[g,"eq","http://www.worldcampus.psu.edu/request-information"]]],[b,null,[[f,"_fp.event.Degrees and Certifications"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates"]]],[b,null,[[f,"_fp.event.Undergraduate Programs"]],
[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/directory/undergraduate/bachelor"]]],[b,null,[[f,"_fp.event.Business Undergraduate"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/business-bachelors/overview"]]],[b,null,[[f,"_fp.event.Information Sciences"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/information-sciences-and-technology-bachelors/overview"]]],[b,null,[[f,"_fp.event.Nursing RN to BS"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/nursing-rn-to-bs-bachelors/overview"]]],
[b,null,[[f,"_fp.event.Psychology"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/psychology-bachelors/overview"]]],[b,null,[[f,"_fp.event.Criminal Justice"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/criminal-justice-bachelors/overview"]]],[b,null,[[f,"_fp.event.Psychology Overview"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/psychology-bachelor-of-science/overview"]]],[b,null,[[f,"_fp.event.Security and Risk Analysis"]],[[g,"eq",
"http://www.worldcampus.psu.edu/degrees-and-certificates/security-and-risk-analysis-bachelors/overview"]]],[b,null,[[f,"_fp.event.Law and Society Overview"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/law-and-society-bachelors/overview"]]],[b,null,[[f,"_fp.event.Human Development and Family Studies"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/human-development-and-family-studies-bachelors/overview"]]],[b,null,[[f,"_fp.event.Undergrad Finance"]],[[g,"eq",
"http://www.worldcampus.psu.edu/degrees-and-certificates/finance-bachelors/overview"]]],[b,null,[[f,"_fp.event.Letters"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/letters-arts-and-sciences-bachelors/overview"]]],[b,null,[[f,"_fp.event.Business Courses"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/business-bachelors/courses"]]],[b,null,[[f,"_fp.event.Economics Overview"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/economics-bachelor-of-science/overview"]]],
[b,null,[[f,"_fp.event.Information Sciences Courses"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/information-sciences-and-technology-bachelors/courses"]]],[b,null,[[f,"_fp.event.Organizational Leadership"]],[[g,"eq","http://www.worldcampus.psu.edu/degrees-and-certificates/organizational-leadership-bachelors/overview"]]])}("p-2-QREZmSntvyD",window,document)}catch(nfe$$4){}quantserve();try{window.smarttagdata&&window._qevents.push(window.smarttagdata),window.qcdata&&window._qevents.push(window.qcdata)}catch(nfe$$5){};